//! Console entry point for the hello MCP server.
//!
//! The transport is chosen by `MCP_TRANSPORT`:
//!
//!   * `stdio` (default) — for MCP clients that launch the server as a subprocess.
//!   * `http` — streamable HTTP on `HOST:PORT` (the container default),
//!     serving the MCP endpoint at `/mcp`.
//!
//! Environment variables:
//!   APP_NAME       display name reported by `server_info` (default: mcp-hello-rust-server)
//!   MCP_TRANSPORT  `stdio` (default) or `http`
//!   HOST, PORT     bind address for the `http` transport (default: 127.0.0.1:8000)

use anyhow::Result;
use rmcp::{
    transport::streamable_http_server::{
        session::local::LocalSessionManager, StreamableHttpService,
    },
    ServiceExt,
};
use tracing_subscriber::{fmt, EnvFilter};

use mcp_hello_rust_server::server::{self, Hello};

#[tokio::main]
async fn main() -> Result<()> {
    // Log to stderr. The stdio transport owns stdout for the JSON-RPC stream, so
    // logs must never go there — writing to stdout would corrupt the protocol.
    fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .init();

    let transport = std::env::var("MCP_TRANSPORT").unwrap_or_else(|_| "stdio".to_string());

    match transport.as_str() {
        "http" => run_http().await,
        "stdio" => run_stdio().await,
        other => {
            anyhow::bail!("unsupported MCP_TRANSPORT '{other}'; expected 'stdio' or 'http'")
        }
    }
}

/// Serve over stdio: read requests from stdin, write responses to stdout.
async fn run_stdio() -> Result<()> {
    tracing::info!("starting {} over stdio", server::app_name());
    let service = Hello::new()
        .serve((tokio::io::stdin(), tokio::io::stdout()))
        .await?;
    service.waiting().await?;
    Ok(())
}

/// Serve over streamable HTTP, exposing the MCP endpoint at `/mcp`.
async fn run_http() -> Result<()> {
    let host = std::env::var("HOST").unwrap_or_else(|_| "127.0.0.1".to_string());
    let port: u16 = std::env::var("PORT")
        .ok()
        .and_then(|p| p.parse().ok())
        .unwrap_or(8000);

    // A fresh Hello per session; the router is generated by the #[tool_router] macro.
    let service = StreamableHttpService::new(
        || Ok(Hello::new()),
        LocalSessionManager::default().into(),
        Default::default(),
    );
    let app = axum::Router::new().nest_service("/mcp", service);

    let listener = tokio::net::TcpListener::bind((host.as_str(), port)).await?;
    tracing::info!(
        "starting {} over streamable HTTP at http://{host}:{port}/mcp",
        server::app_name()
    );

    axum::serve(listener, app)
        .with_graceful_shutdown(async {
            let _ = tokio::signal::ctrl_c().await;
        })
        .await?;
    Ok(())
}
